---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mteucb：Uniform Confidence Band for the Marginal Treatment Function (tative).

<!-- badges: start -->
<!-- badges: end -->

The **mteucb** package cmputes  uniform confidence bands for the MTE function proposed in Okui and Tsuda (2024+). A uniform confidence band covers the true function with a prespecified probability. These bands are used to make statistical inferences on the shape of the MTE function. Uniform confidence bands are particularly useful because they can visualize the statistical uncertainty behind the estimated MTE function.

## Installation

You can install the development version of mteucb from GitHub:

``` r
# install.packages("devtools") if necessary
devtools::install_github("TXT872/mteucb",build_vignettes = TRUE)
```

## Vignette

For more detalis, see the package vignette with:
``` r
# Getting Started with the mteucb Package Vignette
vignette("mteucb")
```

## References

-Okui, R. & Tsuda, T. (2024+).
Uniform Confidence Band for Marginal Treatment Effect Function.
will be available on arXiv.
